### ISSUE TITLE
Antonio Ojea request for joinin

### ISSUE THREAD

**Issue by aojea** [theopenlab/joinin#1]
Working on the problems that are common and span across different communities in an isolated manner is not beneficial for the ecosystem since what is done by each of these communities individually can potentially be shared by others who are working on solving similar problems. This includes but is not limited to improved way of working, alignment on best practices, and tooling re-use.

Here are some ways to support OpenLab:

* Additional infrastructure (commodity hardware, cloud resources, etc)
* Engineering support (developers, project management, software support)
* QA, QE, and test (unit, integration, e2e, scenario) builders.
* Software/application and tooling integrations
* Operations support

Support is not limited to only the items listed above. Fill out the form to get in touch with a governance team member.

### Full Name

Antonio Ojea Garcia

### Email

antonio.ojea.garcia@gmail.com
aojeagarcia@suse.com

### Organization

SUSE

### Job Title

Team Lead Openstack Team

### Can logo be placed on openlabtesting.org?
- [x] Yes
- [ ] No

### Interested in sponsoring any of the following?
- [ ] Additional Infrastructure
- [x] Engineering Support
- [x] Product/Project Manager(s)
- [ ] QA, QE, and test builders
- [x] Software/application and tooling integrations
- [x] Operational Support
- [ ] Other

**Comment by mrhillsman** [comment]
Hey @aojea 

Thanks for showing interest in supporting OpenLab. We have meetings every other Monday at 7am and 10am US Central time so attending those are a good way to get involved initially.

Also, it would be great to schedule some time to just get to talk specifically about OpenLab with you 1:1. We will be at the OpenStack PTG next week if you are there but if not please visit https://calendly.com/openlab and click on General Meeting.

**Comment by mrhillsman** [comment]
Hey @aojea 

Great talking with you, will close this issue now, if there is anything else you would like to discuss relevant to this issue let me know or you can re-open in and mention me. https://github.com/theopenlab/resource-requests/issues/new is where you can point folks to and looking forward to working together.
