### ISSUE TITLE
RuiChen is glad to do cross community integration tests in OpenLab

### ISSUE THREAD

**Issue by kiwik** [theopenlab/joinin#2]
Working on the problems that are common and span across different communities in an isolated manner is not beneficial for the ecosystem since what is done by each of these communities individually can potentially be shared by others who are working on solving similar problems. This includes but is not limited to improved way of working, alignment on best practices, and tooling re-use.

Here are some ways to support OpenLab:

* Additional infrastructure (commodity hardware, cloud resources, etc)
* Engineering support (developers, project management, software support)
* QA, QE, and test (unit, integration, e2e, scenario) builders.
* Software/application and tooling integrations
* Operations support

Support is not limited to only the items listed above. Fill out the form to get in touch with a governance team member.

### Full Name
RuiChen (陈锐)
@kiwik in Github.com
[Rui Chen](https://launchpad.net/~kiwik-chenrui) in OpenStack.org
### Email
chenrui.momo@gmail.com
### Organization
Huawei
### Job Title
OpenStack Opensource Team Manager
### Phone
NA
### Can logo be placed on openlabtesting.org?
- [x] Yes
- [ ] No

### Interested in sponsoring any of the following?
- [ ] Additional Infrastructure
- [x] Engineering Support
- [x] Product/Project Manager(s)
- [x] QA, QE, and test builders
- [x] Software/application and tooling integrations
- [x] Operational Support
- [ ] Other

### Any additional questions, concerns, or comments?
Do integration tests with OpenStack, Kubernetes, Terraform and Ansible, make me learn lots, would like to share my experience, get new ideas in OpenLab.

**Comment by mrhillsman** [comment]
@kiwik is this just for testing?

**Comment by kiwik** [comment]
@mrhillsman this is a sample for new member, I will move it into theopenlab/openlab , then remove this repo.

**Comment by kiwik** [comment]
Replaced by https://github.com/theopenlab/openlab/issues/113
